// Generated by gencpp from file assignment_2_2022/StatInf.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_STATINF_H
#define ASSIGNMENT_2_2022_MESSAGE_STATINF_H

#include <ros/service_traits.h>


#include <assignment_2_2022/StatInfRequest.h>
#include <assignment_2_2022/StatInfResponse.h>


namespace assignment_2_2022
{

struct StatInf
{

typedef StatInfRequest Request;
typedef StatInfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StatInf
} // namespace assignment_2_2022


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2022::StatInf > {
  static const char* value()
  {
    return "31c045aed7eae4a99c1b5f5a71d1bdb1";
  }

  static const char* value(const ::assignment_2_2022::StatInf&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2022::StatInf > {
  static const char* value()
  {
    return "assignment_2_2022/StatInf";
  }

  static const char* value(const ::assignment_2_2022::StatInf&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2022::StatInfRequest> should match
// service_traits::MD5Sum< ::assignment_2_2022::StatInf >
template<>
struct MD5Sum< ::assignment_2_2022::StatInfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::StatInf >::value();
  }
  static const char* value(const ::assignment_2_2022::StatInfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::StatInfRequest> should match
// service_traits::DataType< ::assignment_2_2022::StatInf >
template<>
struct DataType< ::assignment_2_2022::StatInfRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::StatInf >::value();
  }
  static const char* value(const ::assignment_2_2022::StatInfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2022::StatInfResponse> should match
// service_traits::MD5Sum< ::assignment_2_2022::StatInf >
template<>
struct MD5Sum< ::assignment_2_2022::StatInfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::StatInf >::value();
  }
  static const char* value(const ::assignment_2_2022::StatInfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::StatInfResponse> should match
// service_traits::DataType< ::assignment_2_2022::StatInf >
template<>
struct DataType< ::assignment_2_2022::StatInfResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::StatInf >::value();
  }
  static const char* value(const ::assignment_2_2022::StatInfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_STATINF_H
